version: "3.9"

services:
  backend:
    build:
      context: ./maatia
    container_name: maatia-backend
    ports:
      - "8080:8080"
    networks:
      - maatia-net

  frontend:
    build:
      context: ./maatiafrontend
    container_name: maatia-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    networks:
      - maatia-net

networks:
  maatia-net:
